### ISSUE TITLE
Add NDC data

### ISSUE THREAD

**Issue by JGuetschow** [JGuetschow/UNFCCC_non-AnnexI_data#1]
Add data fro the submission of the Nationally Determined Contributions (NDCs) to the dataset. For quantification of the emissions implied by the NDCs as submitted by countries the emissions data submitted with the NDCs are the first priority data source.
All NDC submission are available from the [NDC registry](https://www4.unfccc.int/sites/NDCStaging/Pages/All.aspx).

The format is different from the BUR and NC submissions thus new code is needed for the downloader.

TODOs are:
 

- [ ] Write downloader that uses two steps like the BUR and NC downloaders. 
  - get list of submissions including their URLs 
  - download the data and store it in the folder structure for UNFCCC data
- [ ] Add information to README
- [ ] Retrieve all submissions and add to repository

**Comment by rgieseke** [comment]
NDC URLs and downloads are available in this repo

https://github.com/openclimatedata/ndcs
http://ndcs.openclimatedata.net/

In https://github.com/openclimatedata/national-climate-plans/ they are combined with https://github.com/openclimatedata/indcs to get the latest (preferably English) version for each party.

**Comment by JGuetschow** [comment]
Great! Probably best to look into possibilities to integrate that directly without duplicating code.

**Comment by rgieseke** [comment]
Depending on how you want to run it, just doing
`pd.read_csv("https://github.com/openclimatedata/ndcs/raw/main/data/ndcs.csv")`
might just work ...

**Comment by rgieseke** [comment]
It's also a Data Package so you could also use `pandas-datapackage-reader`.

**Comment by JGuetschow** [comment]
pd.read_csv works fine.

**Comment by JGuetschow** [comment]
done. push is underway.
